<?php

namespace api\v1\lib\common;

enum ResErrCodes: string {
	case UNKNOWN = 'UNKNOWN';
	case INCOMPLETE = 'INCOMPLETE';
	case INVALID = 'INVALID';
	case UNAUTHORISED = 'UNAUTHORISED';

	case SIGN_UP_USERNAME_TAKEN = 'SIGN_UP_USERNAME_TAKEN';
	case SIGN_UP_EMAIL_TAKEN = 'SIGN_UP_EMAIL_TAKEN';

	case SIGN_IN_INVALID_CREDENTIALS = 'SIGN_IN_INVALID_CREDENTIALS';
	case SIGN_IN_USER_NOT_FOUND = 'SIGN_IN_USER_NOT_FOUND';
}
